OMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//drivers/utilities:onos-drivers-utilities',
    '//protocols/netconf/api:onos-protocols-netconf-api',

]

TEST_DEPS = [
    '//lib:TEST_ADAPTERS',
    '//core/api:onos-api-tests',

]

osgi_jar_with_tests (
    deps = COMPILE_DEPS,
    test_deps = TEST_DEPS,
    resources_root = 'src/main/resources',
    resources = glob(['src/main/resources/**']),

)

onos_app (
    title = 'Oplink device drivers',
    category = 'Drivers',
    url = 'http://onosproject.org',
    description = 'ONOS Oplink device drivers application.',
    required_apps = [ 'org.onosproject.netconf'  ],

)
